export interface IOrder {
  buyerAddr: string;
  buyerEmail: string;
  buyerName: string;
  buyerTel: string;
  buyerZipCode: string;
  companyCd: string;
  customData: string;
  customerUid: string;
  escrow: string;
  merchantUid: string;
  orderDate: string;
  orderNo: string;
  orderPrice: string;
  orderTypeCd: string;
  orderTypeNm: string;
  payAmount: string;
  payMethod: string;
  payName: string;
  pg: string;
  resultStatusCd: "SP013001" | "SP013002" | "SP013003" | "SP013004";
  resultStatusNm: "확인중" | "재고없음" | "환불요청" | "처리완료";
  shippingPrice: string;
  statusCd: string;
  statusNm: string;
  userId: string;
  request: string;
}

export interface IOrderedProduct {
  calorie: string;
  carb: string;
  categoryCd: string;
  categoryNm: string;
  cholesterol: string;
  dietNo: string;
  dietSeq: string;
  distributerBizNo: string;
  distributerNm: string;
  fat: string;
  fiber: string;
  freeShippingPrice: string;
  freeShippingYn: string;
  itemReportNo: string;
  link1: string;
  link2: string;
  mainAttId: string;
  mainAttUrl: string;
  minQty: string;
  orderNo: string;
  platformNm: string;
  price: string;
  productNm: string;
  productNo: string;
  protein: string;
  qty: string;
  saturatedFat: string;
  servingSize: string;
  shippingPrice: string;
  sodium: string;
  subCategoryCd: string;
  subCategoryNm: string;
  sugar: string;
  tags: string;
  transFat: string;
}
