export interface IOrderedProduct {
  [key: string]: string;
  tags: string;
  price: string;
  categoryCd: string;
  subCategoryCd: string;
  productNo: string;
  calorie: string;
  carb: string;
  protein: string;
  fat: string;
  companyCd: string;
  userId: string;
  dietNo: string;
  statusCd: string;
  orderNo: string;
  qty: string;
  productNm: string;
  minQty: string;
  shippingPrice: string;
  freeShippingPrice: string;
  freeShippingYn: string;
  servingSize: string;
  sodium: string;
  sugar: string;
  fiber: string;
  cholesterol: string;
  transFat: string;
  saturatedFat: string;
  manufacturerNm: string;
  manufacturerBizNo: string;
  distributerNm: string;
  distributerBizNo: string;
  platformNm: string;
  itemReportNo: string;
  mainAttId: string;
  subAttId: string;
  link1: string;
  link2: string;
  categoryNm: string;
  subCategoryNm: string;
  mainAttUrl: string;
  subAttUrl: string;
  pg: string;
  payMethod: string;
  payName: string;
  payAmount: string;
  buyerName: string;
  buyerTel: string;
  buyerEmail: string;
  buyerAddr: string;
  buyerZipCode: string;
  merchantUid: string;
  customData: string;
  appScheme: string;
  escrow: string;
  customerUid: string;
  orderPrice: string;
  buyDate: string;
  productShippingPrice: string;
  statusNm: string;
  orderTypeCd: string;
  orderTypeNm: string;
}

export interface IOrder {
  statusNm: "checking" | "complete" | "noStock" | "refund" | string;
  buyerNm: string;
  contact: string;
  address: string;
  price: number;
  orderDate: string;
  request: string;
  orderNo: string;
}
